### ISSUE TITLE
Back button issue & Compatible browsers?

### ISSUE THREAD

**Issue by arjunmenon** [miguel-perez/smoothState.js#100]
Hi
What are the supported browsers, with and without animations?
In non-compatible browsers, it does not seem to fallback to default browser page load method. Is it?

I also noticed one thing, when pressing the back button of browser, for pages without "smoothState", suppose you had clicked a link from the footer and then taken to a new page. When clicking back button, browser takes you all the way down to the footer, even without "hash id". It automatically shows that section. But with "smoothState" that does not happen. For content-heavy pages, it will be a little inconvenient.

For animation, is there a slide from bottom/slide from top animation?

Thanks.

**Comment by miguel-perez** [comment]
smoothState will [not run](https://github.com/miguel-perez/smoothState.js/blob/master/jquery.smoothState.js#L15) if the browser does not support pushState. As far as animations go, you can try using canIUse: http://caniuse.com/#feat=css-animation
