### ISSUE TITLE
Update DOM elements outside of $container

### ISSUE THREAD

**Issue by pudgereyem** [miguel-perez/smoothState.js#103]
## smoothState.js version tested:
 - Version 0.5.1

## Description
On the website I'm building now I have information attached to `<body>` such as `id`, `classes` and `styles`. Like below:

`<body id="project-name" class="project single theme-dark" style="background:white">`

..in order to control the page's:

- background color
- color theme (dark/white).

I initialize smoothState on a div #main and when I click a link everything under #main gets updated. The problem is that `body` not gets updated.

## Possible solution:
My first approach to fix this was to use the callback `onEnd`, but none of the variables passed to the `render` function (`url, $container, $content`) holds any information about the `<body>`.  At least to my knowledge – am I missing something?

Since I couldn't solve this with the callback functions I made changes to jquery.smoothState.js. What I did was to extend the `storePageIn` function, adding information to the object variable with a new key `meta`. See code below:

```
storePageIn: function (object, url, $html) {
    $html = ($html instanceof jQuery) ? $html : utility.htmlDoc($html);
    // Add meta information
    // Added by @pudgereyem
    var meta = {}
    meta.bodyId = $html.find( 'body' ).attr( 'id' );
    meta.bodyClasses = $html.find( 'body' ).attr( 'class' );
    meta.bodyCSS = $html.find( 'body' ).attr( 'style' );

    object[url] = { // Content is indexed by the url
        status: "loaded",
        title: $html.find("title").text(), // Stores the title of the page
        html: $html, // Stores the contents of the page
        meta: meta
    };
    return object;
},
```

..and then I also extended the function `updateContent` to actually update `body`:

```
/** Updates the contents from cache[url] */
updateContent = function (url) {
    // If the content has been requested and is done:
    var containerId = '#' + $container.prop('id'),
        $content    = utility.getContentById(containerId, cache[url].html);

    if($content) {
        document.title = cache[url].title;

        // Update body ID, classes and style
        // Added by @pudgereyem
        $body.removeClass().addClass(cache[url].meta.bodyClasses);
        $body.attr('id', cache[url].meta.bodyId);
        $body.attr('style', cache[url].meta.bodyCSS);
...
```

## Discussion
- Wouldn't it make sense if the callbacks provided offer the complete ajax response from the page that gets fetched? So users have greater freedom and not having to change the actual code of this script.

- What do you think about extending the code with `meta information` about the page being fetched like I suggested above?

**Comment by timrourke** [comment]
I hope he notices. Thanks to @jorisvm as I've found this incredibly useful myself.

**Comment by miguel-perez** [comment]
This has been merged in, yay! Sorry it took so long (:

@pudgereyem can this be closed out?

**Comment by BeatLaG** [comment]
Hi,
I have not a clear idea about the modification proposed by @pudgereyem . Is it now included within the plugin core?

I really need to maintain the body out from the ajax container because it is needed for Wordpress and Woocommerce. The engine adds automatically some specific classes to body depending on the page as you know and the plugin is not working for this proposal actually.

So could somebody guide me a little about how to achieve this, please?

Thanks!

**Comment by benjamingeorge** [comment]
I agree this needs documentation.  I need access to the entire html response so I can dynamically update classes on the body element.

**Comment by daltonrooney** [comment]
Agreed, I need this as well, and the feature that was merged in previously has been removed. Any ideas on how to update the body classes when the page is updated?

**Comment by pudgereyem** [comment]
Hey @benjamingeorge and @daltonrooney,
you can access the _full ajax response_ from the `cache` property. This was merged in September 28; https://github.com/miguel-perez/smoothState.js/pull/206

So in `onReady` callback you can do something like this:

```
var url = smoothState.href // <-- get the current url
var doc = smoothState.cache[url].doc // <-- full html response
```

..and with that you can whatever you want, such as update body ID, classes and style.

> I personally also use [a script](https://gist.github.com/cowboy/742952#file-jquery-ba-htmldoc-js) which helps makes the doc prettier so I can use jQuery methods such as `find` to get the body id, classes etc. Feel free to check out [this code](http://pudge.se/NrQ4) that I've written in CoffeeScript that probably does something similar that you want to achieve.

---

@miguel-perez I could see that many people are doing exactly this for their projects. Maybe I should go ahead and add a demo for this.

**Comment by daltonrooney** [comment]
@pudgereyem Thanks very much for that info - that works for me and the htmlDoc script was exactly what I needed to easily pull the classes out and add them to the new page. Cheers!

**Comment by pudgereyem** [comment]
@daltonrooney Awesome, glad to hear!

**Comment by aastudio** [comment]
As far as I see : 
```
smoothState.cache[url].doc
```
would be now 
```
smoothState.cache[smoothState.href].html
```

**Comment by johanneslamers** [comment]
@pudgereyem Can't get this to work. Do you have a working example?

```
         var $html, doc, meta, url;




                    url = smoothState.href;
                    doc = smoothState.cache[url].doc;
                    $html = $.htmlDoc(doc);
                    meta = {};
                    meta.bodyId = $html.find('body').attr('id');
                    meta.bodyClasses = $html.find('body').attr('class');
                    meta.bodyCSS = $html.find('body').attr('style');
                    $('body').removeClass().addClass(meta.bodyClasses);
                    $('body').attr('id', meta.bodyId);
                    $('body').attr('style', meta.bodyCSS);
```

```
Uncaught TypeError: Cannot read property 'replace' of undefined in htmlDoc

this part: 
 var htmlParsed = html.replace(matchTag, function(tag, slash, name, attrs) {

```

**Comment by intelligence** [comment]
I'm getting "undefined" on console.log(smoothState.href) – what gives?

**Comment by sven-ra** [comment]
url = smoothState.href;
doc = smoothState.cache[url].doc;

it seems like the .doc is not working anymore. Any alternatives?

**Comment by scottblinch** [comment]
@intelligence I encountered the same. I'm able to access it if I save my smoothState initialization to a variable, as outlined here: https://github.com/miguel-perez/smoothState.js#methods-and-properties
