### ISSUE TITLE
Using smoothState with script loaders like head.js, LAB.js, yepnope, etc.  

### ISSUE THREAD

**Issue by Paul-Browne** [miguel-perez/smoothState.js#109]
I'm using [LAB.js](http://labjs.com/) to load my scripts, which is working just fine, except when it comes to using smoothState with them. The first page loads perfectly, but when I load successive pages, the html loads fine but all the plug-ins (except smoothState) fail.
I've set up a [demo repository](https://github.com/Paul-Browne/LALT/tree/master/smooth-state-test) to show you what I mean

**Comment by polikin** [comment]
+1

**Comment by darknailblue** [comment]
+1 It seems like the majority of my JavaScript breaks when navigating from page to page.

**Comment by Jonathlee** [comment]
Have anyone tried to bind all on document ready into a function. And re-initiate the function in the Callback? 

Miguel mentioned this before;
https://github.com/weblinc/jquery.smoothState.js/issues/64#issuecomment-54657406

**Comment by janjaap** [comment]
I've got it working with headjs. In my `<head>` I include the headjs script and define which script file it should load once it loads itself:

``` html
<script type="text/javascript" src="/build/head.load.js" data-headjs-load="/build/scripts.js?v=1.2.5" async></script>
```

scripts.js is loaded on every page request and since headjs doesn't load assets twice, this prevents unnecessary downloads and script executions.

In my scripts.js, I'm loading everything else like so:

``` javascript
head.load([
    {'history': '/node_modules/html5-history-api/history.js'},
    {'jquery': '/bower_components/jquery/dist/jquery.min.js'},
    {'smoothstate': '/build/jquery.smoothState.custom.js'}
]);

head.ready(['history', 'jquery', 'smoothstate'], function () {
    //do epic stuff here

    var content = $('#main').smoothState({
        anchors      : '.navigation a',
        development  : true,
        prefetch     : true,
        pageCacheSize: 0,
        onClick      : function (event) {
            //$(event.currentTarget) gets the clicked anchor element
        },
        onStart      : {
            duration: 0,
            render  : function (url, $container) {
                $body.addClass('is-exiting');
            }
        },
        onEnd        : {
            render: function (url, $container, $content) {
                $container.html($content);
                $body.removeClass('is-exiting');
            }
        }
    }).data('smoothState');
});
```

Note that I'm using a custom smoothState version here, as per [howarkitekter.se, line 3708 and 4194](http://howarkitekter.se/c/themes/how/assets/javascripts/plugins.js) to get the `onClick` callback so that I can capture the event and the element clicked.

**Comment by Paul-Browne** [comment]
So, I managed to fix this. In the end the solution was quite easy. The trick is to add a callback to the `tests.js` script after the new content has been added to the page

``` javascript
callback : function(){
    $.getScript("https://rawgit.com/Paul-Browne/LALT/master/smooth-state-test/js/tests.js");
}
```

**Comment by schalmersdev** [comment]
Any idea about how to get this working with require.js. Its been days and no luck.

**Comment by miguel-perez** [comment]
@schalmersdev we are currently working on researching ways to get smoothState working, erhm, "smoothly" with RequireJS.  It would be great if you could elaborate a little on some of the issues you're running into in the discussion on #78
