### ISSUE TITLE
New content cover old content

### ISSUE THREAD

**Issue by tsi** [miguel-perez/smoothState.js#112]
Hi,
I'd like for the new content to enter by covering the old one.
The examples show how it is replacing the old content.
I know of ```pageCacheSize``` which is great but doesn't solve my issue.
Is it possible to append new content to the old one instead of replacing it?
Thanks

**Comment by corysimmons** [comment]
Couldn't you do this by simply modifying your CSS animations and the `duration`?

**Comment by miguel-perez** [comment]
@tsi have you been able to figure this out? let me know.

**Comment by tsi** [comment]
No, I ended up using jQuery-mobile for that.
