### ISSUE TITLE
Your typical demo is buggy in latest Firefox

### ISSUE THREAD

**Issue by baoagency** [miguel-perez/smoothState.js#121]
**smoothState.js version tested:**
- Version Unknown, couldn't find this information. Latest version downloaded as of 17th Feb 2015

**Browser versions or Packager version tested against:**
- Firefox 35.0.1

**Description:**
- When you click the two links in the typical demo page the animation is played once through on the existing page prior to showing the next page. So for example on your demo page (URL below), the process would be as follows: Click a page link at the top to go to another page. The content already on show fades out then fades back in again (like a flash). After that the next page is faded in to replace it.
  No errors are returned.

**Steps to reproduce the problem:**
- Click the two links on the page, Home or About.

**The result that was expected:**
- The existing content already on show should just fade out after you click a link to another page

**The result that occurs instead:**
- The existing content fades out and then back in again (like a flash) after clicking a link

**The url to testcase:**
http://weblinc.github.io/jquery.smoothState.js/demos/typical/

Referring to this demo page: http://weblinc.github.io/jquery.smoothState.js/demos/typical/

**Comment by cstyves** [comment]
There's a small fix, you can add : "pageCacheSize: 100, prefetch: true,". (The fix isn't perfect but the flashing content will be gone)

$(function() {
    var $body = $('html, body');
    var content = $('#scene').smoothState({
    // Runs when a link has been activated
    pageCacheSize: 100,
    prefetch: true,
    onStart: {
     ...
    }
  }).data('smoothState');
});

**Comment by miguel-perez** [comment]
This was fixed with #156
