### ISSUE TITLE
Access to anchor object that triggered the smoothState?

### ISSUE THREAD

**Issue by itsmattsoria** [miguel-perez/smoothState.js#122]
Is there any way to access the anchor object that triggered the smoothState?

My use case is this: I want all anchors to trigger smoothState, but I only want to call the `toggleAnimationClass` when certain anchors are triggered. 

So in the end I was hoping to do something like:

```
onStart: {
  duration: 500,
  render: function (url, $container, $anchor) {
    if ($anchor.is('.animate-it')) {
      content.toggleAnimationClass('is-exiting');
    }
  }
}
```

It's absolutely possible that this is already there and I'm just missing it.
If not, any thoughts on this?

**Comment by miguel-perez** [comment]
@poopsplat can you explain the reasoning behind this feature? What problem does it solve?

**Comment by miguel-perez** [comment]
This has been added on the `onBefore` method.
