### ISSUE TITLE
smoothstate.js works perfectly, but CSS animations are not triggered

### ISSUE THREAD

**Issue by achalv** [miguel-perez/smoothState.js#126]
Hello!

I'm using smoothstate in my portfolio website – it works just fine, except for the fact that CSS animations are not triggered when a new page fragment is loaded, which is weird since I just copied over code from the demo. Tested in Safari, FF and Chrome, but to no avail.

I don't think this is a known/common issue. I'm using v0.5.2 of smoothstate.js, if that helps. Please let me know if posting my code will help figure out what's wrong.

Thank you!

**Comment by Jonathlee** [comment]
any link to your site plz?

Before copy code and direct apply, we suggest you to really go through and have an overview understand on how it works bcz smoothstate is slightly an advanced plugin, required better understand how it actually works.

CSS3 animate; prefix such as -webkit, -moz, may required and the class overlaying is important as well.

You may check out my example > http://jonathlee.com

**Comment by achalv** [comment]
@Jonathlee I went through it and understood how it works. I used code from the demo because it fit my use case perfectly. When that didn't work, I went ahead and set it up myself, bit by bit. That didn't work either.

I checked for the usual suspects like vendor prefixes and such, but no dice. I'll post a link shortly.
Thanks!

**Comment by achalv** [comment]
@Jonathlee This is it – http://achalv.com/work/new/work.html

**Comment by Jonathlee** [comment]
Replace your css from your line 253 with the below to try

```
/*
 * CSS Animations
 * Don't forget to add vendor prefixes!
 */


/* --------------- */

.m-scene.is-exiting > .content > .scene-element {
  -webkit-animation-direction: alternate-reverse;
  animation-direction: alternate-reverse; }


.m-scene .scene_element--fadein{
  animation: fadeIn linear 1s;
  animation-iteration-count: 1;
  transform-origin: 50% 50%;
  animation-fill-mode:forwards; /*when the spec is finished*/
  -webkit-animation: fadeIn linear 1s;
  -webkit-animation-iteration-count: 1;
  -webkit-transform-origin: 50% 50%;
  -webkit-animation-fill-mode:forwards; /*Chrome 16+, Safari 4+*/ 
  -moz-animation: fadeIn linear 1s;
  -moz-animation-iteration-count: 1;
  -moz-transform-origin: 50% 50%;
  -moz-animation-fill-mode:forwards; /*FF 5+*/
  -o-animation: fadeIn linear 1s;
  -o-animation-iteration-count: 1;
  -o-transform-origin: 50% 50%;
  -o-animation-fill-mode:forwards; /*Not implemented yet*/
  -ms-animation: fadeIn linear 1s;
  -ms-animation-iteration-count: 1;
  -ms-transform-origin: 50% 50%;
  -ms-animation-fill-mode:forwards; /*IE 10+*/
}

@keyframes fadeIn{
  0% {
    opacity:0;
    transform:  scaleX(1.50) scaleY(1.50) ;
  }
  100% {
    opacity:1.00;
    transform:  scaleX(1.00) scaleY(1.00) ;
  }
}

@-moz-keyframes fadeIn{
  0% {
    opacity:0;
    -moz-transform:  scaleX(1.50) scaleY(1.50) ;
  }
  100% {
    opacity:1.00;
    -moz-transform:  scaleX(1.00) scaleY(1.00) ;
  }
}

@-webkit-keyframes fadeIn {
  0% {
    opacity:0;
    -webkit-transform:  scaleX(1.50) scaleY(1.50) ;
  }
  100% {
    opacity:1.00;
    -webkit-transform:  scaleX(1.00) scaleY(1.00) ;
  }
}

@-o-keyframes fadeIn {
  0% {
    opacity:0;
    -o-transform:  scaleX(1.50) scaleY(1.50) ;
  }
  100% {
    opacity:1.00;
    -o-transform:  scaleX(1.00) scaleY(1.00) ;
  }
}

@-ms-keyframes fadeIn {
  0% {
    opacity:0;
    -ms-transform:  scaleX(1.50) scaleY(1.50) ;
  }
  100% {
    opacity:1.00;
    -ms-transform:  scaleX(1.00) scaleY(1.00) ;
  }
}


```

**Comment by achalv** [comment]
@Jonathlee Thanks, I did that and it works. But it flashes once before replacing the content, and then fades in again. Do you know what might be causing this?

Maybe it's adding classes prematurely?

**Comment by Jonathlee** [comment]
It was creating a fadeIn animation, try changing the animation duration to 0 (in source.js)

```
onStart: {
          duration: 0,
```

**Comment by achalv** [comment]
Managed to fix it.

Thanks for your help, @Jonathlee!
