### ISSUE TITLE
$(document).ready() Events after SmoothState runs

### ISSUE THREAD

**Issue by JasonEtco** [miguel-perez/smoothState.js#129]
I am trying to have some Javascript run, like this:

```
$(document).ready(function() {
  $('.logoWrapper, .homeInner a').addClass('animated');
});
```

but AFTER smoothstate runs. It works perfectly when I refresh the page, but not when I click a link then hit the back button; the Javascript just doesn't run. I'm a beginner with JS and jQuery, so please don't confuse me. Any help would be great.

Thanks!

**Comment by Jonathlee** [comment]
try using the callback

```
callback : function(url, $container, $content) {
    $(function() {
        $('.logoWrapper, .homeInner a').addClass('animated');
    });

},
```

**Comment by shaneparsons** [comment]
@Jonathlee, Where would that code go?
In my site I have a functions.js page (much like the example), would it have to go in there?
Or is there a way to implement it on the problematic page only?

**Comment by Jonathlee** [comment]
Something like below;

```
callback : function(url, $container, $content) {
    $(function() {
        $('.logoWrapper, .homeInner a').addClass('animated');
    });

},

```

**Comment by miguel-perez** [comment]
@JasonEtco has @Jonathlee's suggestion helped you out?

**Comment by JasonEtco** [comment]
@miguel-perez @Jonathlee Yep that did it, but instead I just made a big function that contains all of my JS and called that in the callback. Thanks!

**Comment by miguel-perez** [comment]
That's fantastic news. If you have any cool smoothState projects to share, share them with us. Our demos are a bit lacking.
