### ISSUE TITLE
Animated scrollTop not working on Chrome nor Firefox

### ISSUE THREAD

**Issue by J4Y4G3** [miguel-perez/smoothState.js#133]
Hello, short version:
installed smoothState, site is up http://stavebnikancelar.eu/ but no animated scrolling seems to be taking place when changing between pages.
Does anybody see the problem?

**Comment by Jonathlee** [comment]
jquery-1.11.0.min.js should be above jquery.smoothState.js

```
<script src="js/jquery.smoothState.js"></script>
<script src="js/functions.js"></script>
<script src="js/jquery-1.11.0.min.js"></script>
```

to below;

```
<script src="js/jquery-1.11.0.min.js"></script> <!-- JQuery should be on top of all jqs plugins -->
<script src="js/jquery.smoothState.js"></script>
<script src="js/functions.js"></script>

```

**Comment by J4Y4G3** [comment]
Okaaaaay... thanks a lot, scrolling is fixed, but now lightbox does not work. At least I know where to seek the problem.

I should probably tell smoothState not to start when the anchor points to an image... used no-smoothstate. Problem solved

**Comment by Alex-APS** [comment]
@J4Y4G3 Did you ever get the lightbox to work?
