### ISSUE TITLE
Uncaught TypeError: Cannot read property 'html' of undefined

### ISSUE THREAD

**Issue by ryanwake01** [miguel-perez/smoothState.js#134]
I am getting this error when loading pages transitions. 
Site: http://ryanwake.com/gramacy/

I have also noticed this message in the console that I am not quite sure what it means. (XHR finished loading: GET "http://ryanwake.com/gramacy/r_packages/reglogit/".)
![screenshot 2015-03-09 16 21 09](https://cloud.githubusercontent.com/assets/5551191/6577125/a17dacbe-c709-11e4-8c12-ca39c53e4553.png)

I am using Chrome on a Mac if that matters.

**Comment by Jonathlee** [comment]
I can't guarantee a fix, but you can try the below;

```
async="false"
```

change it to true

```
async="true"
```

**Comment by miguel-perez** [comment]
@ryanwake01 are you still having this issue?

**Comment by erbridge** [comment]
I've had this issue on 0.5.2, particularly when fetching a lot of pages at once to try and work around #156. I assumed it was an issue with my pages and didn't look into it too much (I had the same issue when I first tried smoothState, too, but it was solved by using an id as the selector, IIRC).

**Comment by miguel-perez** [comment]
@erbridge can you tell me if this is still an issue with the latest version of smoothState?

**Comment by erbridge** [comment]
Doesn't happen with 0.5.43.
