### ISSUE TITLE
Demo page isn't working correctly

### ISSUE THREAD

**Issue by JohnnyWalkerDigital** [miguel-perez/smoothState.js#141]
I'm viewing in the latest version of Chrome and whenever you click on a link the page fades out, appears again, and gets a janky page reload.

http://weblinc.github.io/jquery.smoothState.js/demos/typical/index.html

Hmm.

**Comment by jinsupark** [comment]
I'm getting the same issue, I boiled my code down to the very minimum to figure out the issue but everytime I click the link the fadeout animation happens but then it REappears before switching. Don't know why..

**Comment by miguel-perez** [comment]
@JohnnyWalkerDesign is this issue still happening on the new demo link?

**Comment by JohnnyWalkerDigital** [comment]
This issue is still happening, exactly like I said before: http://miguel-perez.github.io/smoothState.js/demos/typical/index.html

**Comment by miguel-perez** [comment]
@JohnnyWalkerDesign I'm pretty sure this is fixed with #156, can you confirm?

**Comment by miguel-perez** [comment]
Closing for now, I'll re-open if it's still an issue.

**Comment by JohnnyWalkerDigital** [comment]
Yep, looks fixed now!

**Comment by miguel-perez** [comment]
Yay!! Thanks for confirming.
