### ISSUE TITLE
Old content being animated, then replaced with new animation and content

### ISSUE THREAD

**Issue by JohnnyWalkerDigital** [miguel-perez/smoothState.js#142]
Not sure how to go about fixing this. Is it a timing issue perhaps?

I have a pretty simple setup. I'm using Animate.css and SlideInRight for the animated content and FadeIn for the is-exiting animation.

The content fades out, as expected, but sometimes the _same_ (ie. old) content is then slide in from the right, only to be replaced moments later by the correct, new, content sliding in from the right.

What do I need to tweak to make these transitions work correctly? Obviously I only want the slideInRight animation to fire once the new page content is actually loaded. What I can do about this? (Perhaps there's a way I can only fire the slideInRight from onEnd?)

Thanks.

**Comment by Jonathlee** [comment]
use onProgress to hide the current content (e.g. opacity:0) or hide using Js or 

even toggleClass ('hide') 

CSS
.hide{visibility:hidden}

```
onProgress : {
    duration: 0, // Duration of the animations, if any.
    render: function (url, $container) {
        $('container').hide();
    }
},
```

**Comment by JohnnyWalkerDigital** [comment]
Ah! Of course. That works great. Thanks soo much.

**Comment by balajiram** [comment]
How to integrate smooth state.js with backbone.js to get the transition between view navigation.It will be very helpful for me to integrate transition in my app..
If you have any exmple code please share it

**Comment by fractefactos** [comment]
I have the same situation @balajiram, have you found a way?

**Comment by miguel-perez** [comment]
@balajiram please open a new issue for your question.

@JohnnyWalkerDesign has this helped you out? Can this be closed?
