### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by loximoz** [miguel-perez/smoothState.js#159]
Hi,
I have this issue each time smoothState triger my code on link active

Uncaught TypeError: Cannot read property 'attributes' of undefined

My script is normaly ok, all is whithin the div main id, he show properly the first attributes on laoding but lost himself after..

any advice for me ?
thanks a lot :)

**Comment by miguel-perez** [comment]
Hey @loximoz,

We might be able to help, but we'll need a lot more information about what you're working on so that we can re-create the issue. Here's a quick list of what we'll need: https://github.com/miguel-perez/smoothState.js#how-to-ask-for-help

**Comment by loximoz** [comment]
Hi, 
Thanks for your fast response.i fixed it since few , was my fault with my header who broked the smoothstate attributes copy, cause i declare wrong some.
Thanks a lot again, and great plugin by the way ! 
Regards
Sylvain

Sur 27 avr. 2015 20:02, à 20:02, "Miguel Ángel Pérez" notifications@github.com a écrit:
