### ISSUE TITLE
Uncaught TypeError: html.replace is not a function

### ISSUE THREAD

**Issue by wanecek** [miguel-perez/smoothState.js#160]
**smoothState.js version tested:**
Latest (unable to locate version number)

**Browser versions or Packager version tested against:**
- Chrome 42.0.2311.90 m

**Description:**
Upon the second consecutive change of page (e.g. trying to navigate from the startpage, and then back), the html fails to inject into the page. In the console, an error is reported from the smoothState.min.js itself - "Uncaught TypeError: html.replace is not a function".
What strikes me as weird is the fact that it works once, and then breaks. 

For clarification I have recorded the error and uploaded it here: https://youtu.be/QObS90jOUco

**The result that was expected:**
- Navigation to the target page

**The result that occurs instead:**
- failed injection of target content, resulting in the user staying on the same page.

**The url to testcase:**
The problem can be observed at http://wilhelmw.se/dev/.
If you click on any of the project-links (the images) in the black section, that is the section titled 'Utvalda Projekt' (Sorry, Swedish..), you will be renavigated another page. If you then try to go back ( "< Tillbaka", top left corner), the content fails to be injected.

**Possible solution:**
I have done some troubleshooting but am now stuck. What I have established so far is:

**1. jQuery is called and functions**

**2. smoothScroll.js is loaded**

**3. No missing semicolon** <br>
I have looked through the code, and cannot in any case see a place where I have omitted a semicolon. 

**Disclaimer:**
I am still learning Javascript, so it is possible that the solution is painfully obvious, but I hope that isn't the case. I have read other posts without finding a solution which has helped me - asking a question is not my first resort. Other, similar "Uncaught TypeFace" errors seems to have been solved by inlining the code, but this seems like a hacky fix.

**Note:**
I've added a console.log('clicked'), which triggers when you click a link. This was to verify that smoothState actually registers the click.

**Comment by miguel-perez** [comment]
Not sure what the root cause is here, but I might of found a workaround for you:
Replace line 143:

```
htmlParsed  = html.replace(matchTag, function(tag, slash, name, attrs) {
```

with:

```
htmlParsed  = String(html).replace(matchTag, function(tag, slash, name, attrs) {
```

Let me know if that works.

**Comment by wanecek** [comment]
It does indeed! Thank you for the quick reply!

I wonder why this happened - the options for the smoothState functions are taken from the examples.

Once again Miguel, thank you for your help!
