### ISSUE TITLE
onProgress duration

### ISSUE THREAD

**Issue by gcirone** [miguel-perez/smoothState.js#164]
Sorry but is normal at line 368 is options.onStart.duration should be options.onProgress.duration

https://github.com/miguel-perez/smoothState.js/blob/master/jquery.smoothState.js#L368

**Comment by miguel-perez** [comment]
@gcirone I'm not sure what you mean. Could you explain a little more?

**Comment by gcirone** [comment]
Where do you use options.onProgress.duration in plugin. Is i set some value for onProgress.duration  nothing append.

**Comment by gcirone** [comment]
The line change is 370 what i mean
https://github.com/miguel-perez/smoothState.js/blob/master/jquery.smoothState.js#L370

**Comment by miguel-perez** [comment]
Fixed! Thanks for the report @gcirone
