### ISSUE TITLE
Firefox: content not being injected

### ISSUE THREAD

**Issue by mikemedoro** [miguel-perez/smoothState.js#170]
I've been testing the latest version of smoothState(0.7.0) and noticed it is not injecting the new page content in the latest version of Firefox. The page animates out, but the new content never appears. I've inspected #main div container and it appears empty. Again, this is only happening in Firefox and is working great in Chrome and Safari.

**Comment by miguel-perez** [comment]
closing this out, since the other thread #171 has a little more detail.

Thanks for the report!
