### ISSUE TITLE
document.write() failing on Firefox 38

### ISSUE THREAD

**Issue by nikdunn** [miguel-perez/smoothState.js#171]
I'm trying to use smoothState.js and I was testing on Firefox 38 and was getting a blank page on transition. I tracked it down to the storePageIn function. It seems like a bug in firefox, so I created this ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1171039. Is there a more reliable alternative to getting the next page into the cache? I was thinking about using jquery's parseHTML() function.

The smoothState.js demo page looks like it uses a different version of the library. In that version that works in this version of FF it looks to be using jquery to parse the html.

**Comment by miguel-perez** [comment]
@nikdunn The biggest issue with using `$.parseHTML()` is that it removes a handful of tags, including any `body` elements. This is the implementation that was here before and it was removed as it was causing a bug with meta elements and svgs.

see: #105 and #123 

This is super frustrating and I'm open to hearing any ideas.

**Comment by nikdunn** [comment]
I've had this issue in the past (before jQuery became ubiquitous). What I did then seems very anachronistic now and it was very specialized to my application, but I implemented a custom importNode() function along the lines of this article: http://alistapart.com/article/crossbrowserscripting.

That being said, this seems like a terrible solution in this day and age. Unfortunately, it seems like the goal of this plugin requires direct control over how pages are parsed (so you can fix incompatibilities in the browsers using your own javascript shim code) or you just have to accept the dependency on the browser's differing parsing methods.

There's an htmlparser (called htmlparser) for node.js that works in the browser. I've never used it, but you could provide cross-browser compatibility inside your own parsing code. Most things could be handled with simple "createElement()" and "append()" calls (assuming that THOSE work). SVGs and meta tags could be handled in special cross-browser ways. That's really the nuclear option, though. 

I've used hidden iframes to pull in data from other sources and play around with their DOMs. That might be an option as well, but that seems similarly outdated.

Let me ask you this: do you really need the html/head parts of the document? It looks like you're just swapping out the marked div tag with a marked div tag in the new page. That doesn't seem like it would depend on anything in the head tag. If it doesn't, then you could do a deep cloneNode(true) of the documentElement to grab a copy of the current page. Ticket #105 seemed to refer to meta tags inside <div> elements, not the <head> tag. And jquery is known to not properly support parsing of SVG tags. But maybe cloneNode()/hidden iframe would work for those. You could always post-process the output of jquery's parseHTML() and re-add the elements that don't work out of the box using DOM manipulation.

In my other project I found myself reattaching mouse handlers and other things as well. It wasn't too bad handling the outlying cases.

Final option, you could punt and provide the raw HTML in the render function.

**Comment by miguel-perez** [comment]
@nikdunn thanks for your insights, you've given me a lot to think about. I've pushed [some code](https://github.com/miguel-perez/smoothState.js/commit/68b46e2f314e50b0d8ceda0ae8b001c1d78796cc#diff-e3df82de5ebd91b2ce06acbfcf86ef90R394) that will force firefox to reload the page if it can't find the elements it is looking for as a small way to patch the issue. 

I'll keep plugging away see if I can come up with a workaround.

**Comment by miguel-perez** [comment]
It seems that if we eliminate the support for allowing the body or html elements to be defined as the smoothState container, we can simplify this code and do away with this bug.

Might make a few people upset, but I'm okay with it.

**Comment by miguel-perez** [comment]
@nikdunn This should be fixed now! Let me know.

**Comment by nikdunn** [comment]
It looks like it's fixed now. Thanks!
