### ISSUE TITLE
API changes break existing installations

### ISSUE THREAD

**Issue by tobaco** [miguel-perez/smoothState.js#172]
i just updated smoothstate in a project from 0.6.0 to 0.7.0 and wondered why my content was not visible anymore after injection. then i discovered, that you changed the the `onEnd` hook to `onReady` and the `callback` to `onAfter`.
after changing these i got it working again. but now my animations are gone (hard in and out) and i don't have the `url` param in the hooks anymore, which i used to trigger an analytics pageview.

do you have any plans on reintroducing the `url` param?
and ist there a working example with animations?

thanks!

**Comment by miguel-perez** [comment]
@tobaco, the url param should be available to you a few different ways, see the following console.logs:

``` js
$(function(){
  'use strict';
  var $page = $('#main'),
      options = {
        alterRequest: function(request) {
          console.log(request.url);
          return request;
        },
        onBefore: function($currentTarget, $container) {
          console.log($currentTarget.prop('href'), $currentTarget.prop('action'));
        },
        onAfter: function($container, $newContent) {
          console.log(smoothState.href);
        }
      },
      smoothState = $page.smoothState(options).data('smoothState');
});
```

**Comment by miguel-perez** [comment]
Also, in the demo folder there is a csstricks demo that uses animations.

**Comment by miguel-perez** [comment]
CLosing this out, let me know if you have any questions.

**Comment by tobaco** [comment]
thanks!
i will try your approach.
