### ISSUE TITLE
Automatic Google Analytics Integration

### ISSUE THREAD

**Issue by rolandschuetz** [miguel-perez/smoothState.js#183]
I think it would be great if Google Analytics would automatically be tiggered if available.

So adding something like this:

```
if (window.ga) {
  window.ga('send', 'pageview', window.location.pathname || url);
}
```

**Comment by erbridge** [comment]
You actually need `smoothState.href`, not `url`, now, assuming it gets called at on `onAfter`.

Personally, I'm of the opinion that smoothState.js should do as little as possible, but give lots of room for customization.

**Comment by rolandschuetz** [comment]
I think if someone uses Google Analytics, that is what he would want to have. And so it makes both the lives of the user easier, and minimizes our support efforts.

Am I missing a downside here?

**Comment by erbridge** [comment]
I might want to do something other than send a pageview (like using custom events). If this is added, it should at least be optional.

My main objection is that I feel like this could be the start of a slippery slope towards feature bloat: "Hey you guys support GA, why not also Optimizely, KISSmetrics or The Latest Awesome Analytics Tool?" An alternative is to add plugin support and let people write / include components they need, taking the burden off the maintainers of smoothState.

**Comment by koole** [comment]
I completely agree with https://github.com/miguel-perez/smoothState.js/issues/183#issuecomment-111734841 here. While it might be a useful feature for some people, I do not think it should be built in, because that would result in too much bloat.

A plugin system might be better indeed, but that would still increase the file size of smoothstate.

**Comment by miguel-perez** [comment]
I like the idea of making it easy to create plugins with smoothState. I'm with both @Lymi and @erbridge on this one, though. Closing out.

**Comment by lost-end-found** [comment]
In case someone is looking for code to track pageview with Google Analytics, previous comments didn't really worked for me, but helped to come to the solution below 
```
function googleAnalytics() {
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-XXXXXXX-X', 'auto');
  ga('set', 'page', window.location.pathname); // this will track the pageviews as well
  ga('send', 'pageview');
}
```

and then call `googleAnalytics();` on `$(document).ready(function(){});` and `onAfter`

**Comment by rolandschuetz** [comment]
The first part loads the google analytics script, which should only be necessary for the first time. Then you only need the last line.

**Comment by lost-end-found** [comment]
You are absolutely right @rolandschuetz . Some unnecessary lines there.

**Comment by Eugene1984** [comment]
For anyone that struggles with this - Have have spend a lot of hours trying to solve this....

Here's the solution that worked for me:
Add GA to header or footer:
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'xxxxxx', 'auto');
  ga('set', 'anonymizeIp', true);
  ga('send', 'pageview');
</script>

Then on onReady:
window.ga("send", "pageview", window.location.pathname)

Like below.
onReady: {
          duration: 800,
          render: function ($container, $newContent) {
            // Remove your CSS animation reversing class
            $container.removeClass('is-exiting');
            // Inject the new content
            $container.html($newContent);
            $container.addClass('is-animating'); 
            window.ga("send", "pageview", window.location.pathname)
          }
        },

Hope this helps someone.

**Comment by onmarketing** [comment]
Mine is not working for views page in Google Analytics here my coding:

$(document).ready(function() {
    function e() {
        var e = $(".hamburger"),
            a = $(".m-nav"),
            t = $(".wrapper");
        e.click(function(s) {
            e.toggleClass("is-active"), e.toggleClass("mobilenav"), a.toggleClass("show"), t.toggleClass("fixed")
        }), $(function() {
            $(".box").matchHeight()
        }),
        $('a[href*="#"]:not([href="#"])').click(function() {
        if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
            if (target.length) {
                $('html, body').animate({
                    scrollTop: target.offset().top - 100
                }, 1000);
                return false;
            }
        }
    });
    }
    $(function() {
        "use strict";
        var a = $("#main"),
            t = {
                debug: false,
                prefetch: !0,
                anchors: 'a',
                cacheLength: 2,
                onStart: {
                    duration: 500,
                    render: function(e) {
                        e.addClass("is-exiting"), s.restartCSSAnimations()
                    }
                },
                onReady: {
                    duration: 0,
                    render: function(e, a) {
                        e.removeClass("is-exiting"), e.html(a);
                        window.ga("send", "pageview", window.location.pathname)
                    }
                },
                onAfter: function() {
                    e()
                }
            },
            s = a.smoothState(t).data("smoothState")
    }), e(), $("input,textarea").focus(function() {
        $(this).data("placeholder", $(this).attr("placeholder")).attr("placeholder", "")
    }).blur(function() {
        $(this).attr("placeholder", $(this).data("placeholder"))
    })
});

**Comment by Eugene1984** [comment]
Be sure to do a hard refresh CTRL F5 - then check realtime tracking on GA ad you go through the pages. Or try moving window.ga("send", "pageview", window.location.pathname) to onafter.

**Comment by onmarketing** [comment]
Hi,

I'm having problem with Google Tag Manager (one for in head / other one for after body) and won't show other pages in Google Tag Manager for Google Analytics.

Does anyone know about this?

Please let me know ASAP.

Thanks,

Shaun.

**Comment by onmarketing** [comment]
`$(document).ready(function() {
    function e() {
        $(".list.gigs a").hover(function() {
            $($(this).data("link")).toggleClass("show")
        });
        var e = $(".hamburger"),
            a = $(".m-nav"),
            t = $(".wrapper");
        e.click(function(s) {
            e.toggleClass("is-active"), e.toggleClass("mobilenav"), a.toggleClass("show"), t.toggleClass("fixed")
        }), $(".m-nav li a").click(function() {
            t.removeClass("fixed")
        }), $(function() {
            $(".box").matchHeight(), $(".text-box").matchHeight(), $(".course-text-box").matchHeight(), $(".card-block").matchHeight(), $(".card-text").matchHeight()
        }), $(function() {
            var s = $(".page-header");
            $(window).scroll(function() {
                var e = $(window).scrollTop();
                e >= 0 ? s.addClass("down") : s.removeClass("down")
            })
        }), $(".splash-close").click(function() {
            $(".splash-container").removeClass("active"), $(".splash-bg").removeClass("active"), $(".wrapper").removeClass("fixed")
        }), $(".splash-close-link").click(function() {
            $(".splash-container").removeClass("active"), $(".splash-bg").removeClass("active"), $(".wrapper").removeClass("fixed")
        })
    }
    // Add smooth scrolling to all links
    $("a").on('click', function(event) {

        // Make sure this.hash has a value before overriding default behavior
        if (this.hash !== "") {
          // Prevent default anchor click behavior
          event.preventDefault();

          // Store hash
          var hash = this.hash;

          // Using jQuery's animate() method to add smooth page scroll
          // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
          $('html, body').animate({
            scrollTop: $(hash).offset().top - 100
          }, 800, function(){

            // Add hash (#) to URL when done scrolling (default click behavior)
            window.location.hash = hash;
          });
        } // End if
    });
    $(function() {
        "use strict";
        var a = $("#main"),
            t = {
                prefetch: !0,
                cacheLength: 2,
                onStart: {
                    duration: 500,
                    render: function(e) {
                        e.addClass("is-exiting"), s.restartCSSAnimations()
                    }
                },
                onReady: {
                    duration: 0,
                    render: function(e, a) {
                        e.removeClass("is-exiting"), e.html(a)
                    }
                },
                onAfter: function() {
                    e()
                    window.ga("send", "pageview", window.location.pathname)
                }
            },
            s = a.smoothState(t).data("smoothState")
    }), e(), $("input,textarea").focus(function() {
        $(this).data("placeholder", $(this).attr("placeholder")).attr("placeholder", "")
    }).blur(function() {
        $(this).attr("placeholder", $(this).data("placeholder"))
    })
});`

**Comment by onmarketing** [comment]
`$(document).ready(function() {
    function e() {
        $(".list.gigs a").hover(function() {
            $($(this).data("link")).toggleClass("show")
        });
        var e = $(".hamburger"),
            a = $(".m-nav"),
            t = $(".wrapper");
        e.click(function(s) {
            e.toggleClass("is-active"), e.toggleClass("mobilenav"), a.toggleClass("show"), t.toggleClass("fixed")
        }), $(".m-nav li a").click(function() {
            t.removeClass("fixed")
        }), $(function() {
            $(".box").matchHeight(), $(".text-box").matchHeight(), $(".course-text-box").matchHeight(), $(".card-block").matchHeight(), $(".card-text").matchHeight()
        }), $(function() {
            var s = $(".page-header");
            $(window).scroll(function() {
                var e = $(window).scrollTop();
                e >= 0 ? s.addClass("down") : s.removeClass("down")
            })
        }), $(".splash-close").click(function() {
            $(".splash-container").removeClass("active"), $(".splash-bg").removeClass("active"), $(".wrapper").removeClass("fixed")
        }), $(".splash-close-link").click(function() {
            $(".splash-container").removeClass("active"), $(".splash-bg").removeClass("active"), $(".wrapper").removeClass("fixed")
        })
    }
    // Add smooth scrolling to all links
    $("a").on('click', function(event) {

        // Make sure this.hash has a value before overriding default behavior
        if (this.hash !== "") {
          // Prevent default anchor click behavior
          event.preventDefault();

          // Store hash
          var hash = this.hash;

          // Using jQuery's animate() method to add smooth page scroll
          // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
          $('html, body').animate({
            scrollTop: $(hash).offset().top - 100
          }, 800, function(){

            // Add hash (#) to URL when done scrolling (default click behavior)
            window.location.hash = hash;
          });
        } // End if
    });
    $(function() {
        "use strict";
        var a = $("#main"),
            t = {
                prefetch: !0,
                cacheLength: 2,
                onStart: {
                    duration: 500,
                    render: function(e) {
                        e.addClass("is-exiting"), s.restartCSSAnimations()
                    }
                },
                onReady: {
                    duration: 0,
                    render: function(e, a) {
                        e.removeClass("is-exiting"), e.html(a)
                    }
                },
                onAfter: function() {
                    e()
                    window.ga("send", "pageview", window.location.pathname)
                }
            },
            s = a.smoothState(t).data("smoothState")
    }), e(), $("input,textarea").focus(function() {
        $(this).data("placeholder", $(this).attr("placeholder")).attr("placeholder", "")
    }).blur(function() {
        $(this).attr("placeholder", $(this).data("placeholder"))
    })
});`

**Comment by Eugene1984** [comment]
Same issue as Shaun.
