### ISSUE TITLE
"de-active" script on page change?

### ISSUE THREAD

**Issue by jesperlandberg** [miguel-perez/smoothState.js#187]
Hi,

First of thanks for an awesome plugin.

I have a little issue tho, and me being a jquery/js noob I can't seem to solve it. I have a script in a template that looks like this:

```
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('#fullpage').fullpage({
            afterRender: function(){
                var pluginContainer = jQuery(this);
                anchors: [<?php foreach ( $myposts as $post ) : setup_postdata( $post );?>'<?php print str_replace($search, $replace, strtolower (get_the_title())); ?>',<?php endforeach; wp_reset_postdata();?>'facts']
            }
        });
    });
</script>
```

The reason I have put this script in the template is because of the php and because I only want to run it (fullpage.js) on this page only. But because no full page reload is done (correct?) when using smoothstate this script is run on all pages i go to after this one, thus breaking the site. 

How would you go on about running this only on the specific template and reinitalize it when entering it again when using smoothstate?

My smoothstate:

```
$(function(){
  'use strict';
  var options = {
    prefetch: true,
    cacheLength: 2,
    onStart: {
      duration: 250, // Duration of our animation
      render: function ($container) {
        // Add your CSS animation reversing class
        $container.addClass('is-exiting');

        // Restart your animation
        smoothState.restartCSSAnimations();
      }
    },
    onReady: {
      duration: 0,
      render: function ($container, $newContent) {
        // Remove your CSS animation reversing class
        $container.removeClass('is-exiting');

        // Inject the new content
        $container.html($newContent);

      }
    },
    onAfter: function($container, $newContent) {
      $(function(){
        initPage();
        initLoadResize();
      })
    }
  },
  smoothState = $('#main').smoothState(options).data('smoothState');
});
```

**Comment by miguel-perez** [comment]
@ReGGaeBOSS thanks for reaching out, and for the kind words.

We need to keep the Github issue tracker free of personal support request so that we can better manage bugs and enhancements. So I'll need to close this out. Check out the [help section](https://github.com/miguel-perez/smoothState.js#need-help) for some better ways of getting some help with implementation.
