### ISSUE TITLE
smoothState doesn't load all my js files

### ISSUE THREAD

**Issue by whtrbit** [miguel-perez/smoothState.js#188]
Hi there,
I have a problem with loading all my JS files for specific pages. Let's say we have hompage with a.js and b.js

When I'm going to some subpage where at the bottom of the file I have c.js this file is not loading.

Any idea how to fix it?

Best,
G.

**Comment by miguel-perez** [comment]
@gregorcio92, thanks for reaching out. It's pretty difficult to figure out what's going on here without looking at some code.

Can you provide samples of a reduced test case?
