### ISSUE TITLE
Current Page Cached Even Though `cacheLength` is 0

### ISSUE THREAD

**Issue by neon64** [miguel-perez/smoothState.js#194]
Setting `cacheLength` to 0 won't completely stop caching.

If you call `smoothstate.load()`with the URL of the current page you are viewing it will just load from cache and not actually request new content.

Just looking quickly though the source, i think it might be because the cache is being trimmed after the cache is checked not before

```
      // Don't prefetch if we have the content already or if it's a form
      if(cache.hasOwnProperty(settings.url) && typeof settings.data === 'undefined') {
        return;
      }

      // Check the length of the cache and clear it if needed
      cache = utility.clearIfOverCapacity(cache, options.cacheLength);
```

Perhaps changing to this might help?

```
      // Check the length of the cache and clear it if needed
      cache = utility.clearIfOverCapacity(cache, options.cacheLength);

      // Don't prefetch if we have the content already or if it's a form
      if(cache.hasOwnProperty(settings.url) && typeof settings.data === 'undefined') {
        return;
      }
```

**Comment by DigitalMachinist** [comment]
@neon64 I implemented your suggested fix and it seems to work wonderfully. Great suggestion. I'm about to submit a PR with the fix.
