### ISSUE TITLE
Stops working after page has been inactive

### ISSUE THREAD

**Issue by Crustofr** [miguel-perez/smoothState.js#195]
Hi all.
Not entirely sure how to describe the issue in the best way but I will try!

smoothState works fine 99% of the time. Pages load without any issues, my scripts still run fine, all logging is looking fine and so forth. The issue arises when the page has not been changed for a decent amount of time (by which I mean at least 5 minutes if not more, I haven't been able to find out just how long it takes to stop working).

So I have the website open on:
http://mysite.com/pages/staff

Leave the tab, or leave it on the tab but walk away from the computer for however long it might be. I come back and attempt to go to:
http://mysite.com/pages/contact

Instead of going to "http://mysite.com/pages/contact", a full page refresh takes place and I am sent back to "http://mysite.com".

It seems weird that it would work fine endlessly if I am actively using the site, but if it is left on the same page with no interaction for too long, it forces a full page refresh and doesn't even send me to the url I was going to.

Any advice or help would be appreciated.

**Comment by miguel-perez** [comment]
Those links 404, closing.
