### ISSUE TITLE
Im missing the point obviously

### ISSUE THREAD

**Issue by Webdesignwill** [miguel-perez/smoothState.js#214]
Hello there, 

as this is annoying for everyone reading because of it's simplicity, I shall keep it short.

In my Backbone view to which the $el is $('body'), I have an initSmoothState method with the following code inside : 

``` javascript
this.$smoothState = this.$el.smoothState({
  onStart : {
    duration : 2250,
    render : function ($container) {
      alert();
      $container.toggleAnimationClas('is-exiting');
    }
  },
}).data('smoothState');
```

this.$smoothState is instantiated and yet the onStart is never called.

In order to make this work, I am clicking an <a href="#!/somewhere">Somewhere</a> link which isn't being prevented from bubbling.

It's being loaded properly, I can see it in the console.

I simply can't get any of the methods to be invoked on the smoothState object.

What actually invokes this method? Is it listening for a bubbled click or href change or something? It's not clear in the documentation exactly what makes this thing come to life.

Thanks in advance,

Will

**Comment by Webdesignwill** [comment]
I've also been following this small tutorial : https://css-tricks.com/add-page-transitions-css-smoothstate-js/ to no avail if that helps.

**Comment by miguel-perez** [comment]
@Webdesignwill the issue tracker needs to stay clear for bug reports, please see here on how to get implementation help: https://github.com/miguel-perez/smoothState.js#need-help
