### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by croxton** [miguel-perez/smoothState.js#215]
`$body.scrollTop(0);` causes the page to jump to the top on transitions, even if the user has scrolled down to, say, click a link partly down the page. Could this behaviour either be removed or made optional?

Lines 538 - 541

```
  window.setTimeout(function(){
    $body.scrollTop(0);
    $container.trigger('ss.onStartEnd');
  }, options.onStart.duration);
```

**Comment by shrpne** [comment]
Here is pull request, that should fix this https://github.com/miguel-perez/smoothState.js/pull/218

**Comment by miguel-perez** [comment]
@shrpne thanks again for this.
