### ISSUE TITLE
Identifying the referring page?

### ISSUE THREAD

**Issue by paulcarbo** [miguel-perez/smoothState.js#221]
I'd like to identify the referring page with a class visible on the new page. Is there any way to do this? Or is what I'm I'm looking for already built in and I'm unaware of it?

**Comment by ghost** [comment]
You could try adding a class to the body through an onStart callback.

<pre>
onStart: {
  // your other options go here
  render: function($container){
    $('body').addClass('your-identifier');
  }
}
</pre>

**Comment by paulcarbo** [comment]
That's pretty much what I ended up doing. It became obvious to me shortly after I brought it up here. But many thanks for the help.
