### ISSUE TITLE
Background Color Animation

### ISSUE THREAD

**Issue by plnat** [miguel-perez/smoothState.js#230]
Is it possible to change background color (smooth) as well?

**Comment by pudgereyem** [comment]
Hey @plnat,
yes it is! 

If you wan't to change the background color of the `<body>` – which is outside of the smoothState container – you would have to check the ajax response that you can get from the `cache` property. Like this; `smoothState.cache[<--insert url-->].doc`

Also see this discussion on just this matter; https://github.com/miguel-perez/smoothState.js/issues/103#issuecomment-160401967
