### ISSUE TITLE
Is it possible to preload previous/next slides with smoothState?

### ISSUE THREAD

**Issue by corysimmons** [miguel-perez/smoothState.js#242]
We've essentially made a page slider with smoothState that will grab the prev/next posts (WordPress) with arrows to them.

Is it possible to load up the prev/next posts?

**Comment by corysimmons** [comment]
I noticed https://github.com/miguel-perez/smoothState.js#fetchurl but I'm not really sure how to implement it.

**Comment by miguel-perez** [comment]
Should be something like: 

```
// Access smoothState
var smoothState = $('#main').smoothState().data('smoothState');

// Run method
smoothState.fetch('/nextPost.html');
smoothState.fetch('/previousPost.html');
```

**Comment by corysimmons** [comment]
Awesome, will give that a try. Thanks!
