### ISSUE TITLE
Flickity javascript broken when using Smoothstate

### ISSUE THREAD

**Issue by notflip** [miguel-perez/smoothState.js#243]
I'm using flickity as a slider.. And I have a method which listens to a jQuery button event to show the next slide.

When I navigate to the page with the slider using Smoothstate the buttons aren't working anymore.. Not even the thumbnail selection buttons. 

I think this is causing the problem.

```
            render: function ($container, $newContent) {
                 $container.removeClass('is-exiting');
                $container.html($newContent); <-----
            }
```

**Comment by medoingthings** [comment]
I’m using flickity on a site with Smoothstate and it’s working very good.

I think what you’re encountering is not an issue with smoothstate per se. I think you are not initializing flickity again after the content gets exchanged, are you? 

All the javascript modules within the newly loaded content will not be initialized until you do it.

**Comment by sahandii** [comment]
Having the same problem, really can't find the solution to this :/

**Comment by medoingthings** [comment]
@sahandii you need a piece of JavaScript that initializes all your JavaScript modules within the newly injected content

**Comment by sahandii** [comment]
@medoingthings yeah got that to work, flickity too. It's more a plug-in like fullPage.js, It must not be initialized more than once, and I can't find the trick to make it only be that one time, both from a refresh (document.ready) and from the OnReady trigger, when a page transition happens..
I ditched it anyways, but yeah gotta experient more with it at some point..
