### ISSUE TITLE
Smoothstate with Google maps

### ISSUE THREAD

**Issue by goldtoothlogoose** [miguel-perez/smoothState.js#249]
Hi,

Just wondering if someone can point me in the direction of how to get google maps working with smoothstate?

I had google maps loading fine on my static site. I've got smoothstate.js running fine now, and have tried the recommended method of using the onAfter callback detailed [here](http://stackoverflow.com/questions/31928322/making-smoothstate-animations-and-masonry-work-together) to load the document.ready code again. It's not loading the map however, after smoothstate.js ajax's in the page with the map on it.

My js currently looks like this:

```
 ;(function($){
    var  $doc = $(document);

    /** create mod exec controller */
    $.readyFn = {
        list: [],
        register: function(fn) {
            $.readyFn.list.push(fn);
        },
        execute: function() {
            for (var i = 0; i < $.readyFn.list.length; i++) {
                try {
                   $.readyFn.list[i].apply(document, [$]);
                }
                catch (e) {
                    throw e;
                }
            };
        }
    };

    /** run all functions */
    $doc.ready(function(){
        $.readyFn.execute();
    });

    /** register function */
    $.fn.ready = function(fn) {
        $.readyFn.register(fn);
    };

})(jQuery);

$(function(){
  'use strict';
  var $page = $('#main'),
      options = {
        debug: true,
        prefetch: true,
        cacheLength: 2,
        onStart: {
          duration: 500, // Duration of our animation
          render: function ($container) {
            // Add your CSS animation reversing class
            $container.addClass('is-exiting');
            // Restart your animation
            smoothState.restartCSSAnimations();
          }
        },
        onReady: {
          duration: 0,
          render: function ($container, $newContent) {
            // Remove your CSS animation reversing class
            $container.removeClass('is-exiting');
            // Inject the new content
            $container.html($newContent);
          }
        },
        // over a year ago, this was simply callback: function(){}
        onAfter: function($container, $newContent){
          $.readyFn.execute();
        }
      },
      smoothState = $page.smoothState(options).data('smoothState');
});



$(document).ready(function(){

           //Google maps initialise

             window.onload = function () {

                var latlng = new google.maps.LatLng(-37.856520, 145.027979);

                var styles = [
                    {
                        featureType: "landscape",
                        stylers: [
                            { color: '#eeddee' },
                            { saturation: -100 }
                        ]
                    },{
                        featureType: "natural",
                        stylers: [
                            { hue: '#ff0000' },
                            { saturation: -100 }
                        ]
                    },{
                        featureType: "road",
                        stylers: [
                            { hue: '#5500aa' },
                            { saturation: -100 }
                        ]
                    },{
                        featureType: "building",
                        elementType: "labels",
                        stylers: [
                            { hue: '#000066' },
                            { saturation: -100 }
                        ]
                    },{
                        featureType: "poi", //points of interest
                        stylers: [
                            { hue: '#0044ff' },
                            { saturation: -100 }
                        ]
                    }
                ];


                var isTouchDevice = !('ontouchstart' in document.documentElement);

                var myOptions = {
                    zoom: 16,
                    center: latlng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                    disableDefaultUI: true,
                    zoomControl: true,
                    styles: styles,
                    scrollwheel:  false,
                    draggable: isTouchDevice
                };

                map = new google.maps.Map(document.getElementById('map'), myOptions);

                var marker = new google.maps.Marker({
                    position: latlng,
                    title: "Brow 101"
                });

                marker.setMap(map);

            };

});
```

Thanks for any help

**Comment by mcaskill** [comment]
I encountered a similar issue with a project I'm currently working which loaded the Google Maps API in container template (`<script>`) and had an external module that needed re-initializing.

There's a number of issues with the code above, let me take you through each of my observations.

First issue is that the following syntaxes are equivalent:
- `$( document ).ready( handler )`
- `$( handler )`

You're registering the SmoothState (`$()`) and Google Maps (`$(document).ready()`) initializations with the mod exec controller (MEC). So during SmoothState's `onAfter` event, you'd be re-creating a Google Map _and_ a SmoothState instance.

Second issue is that your `onReady` handler for Google Maps attaches the initialization to the window's `onLoad` event. Since SmoothState does page changes using AJAX, the event is only called once on the initial page load. So we can dispense with the `onLoad`.

Below is a reorganized version of your snippet. Changes I've made:
- Added some console logs to see the order of execution;
- Moved initializations of SmoothState and Google Maps to an `app` object;
- The initial `onReady` event (should) execute globally persistent features—such as SmoothState—only once on top of enabling all other (page-specific) features;
- Added a `initGoogleMaps` method—registered with the MEC—which either requests the JS API or creates the map based on whether a map is needed or not;
- Moved the map making process to a `makeGoogleMaps` method;
- Added a `loadGoogleMaps` method for requesting the Google Maps JS API which then calls the `makeGoogleMaps` when ready;
- Map styles removed for sake of the snippet being an example.

```
'use strict';

/**
 * IIFE
 *
 * 1. Create the module execution controller (MEC);
 * 2. Create the application controller for SmoothState and Mapping;
 * 3. Attach our app's initializer and the MEC's executor to jQuery's Ready handler (executes once);
 * 4. Replace jQuery's Ready handler with the MEC's registrar;
 * 5. Attach a module to the MEC (executes on jQuery's onReady event and all SmoothState onAfter events);
 */
var app = {};

;(function($) {
    var $doc = $(document);

    /** [1] */
    $.readyFn = {
        list: [],
        register: function(fn) {
            console.log('Module Registered');

            $.readyFn.list.push(fn);
        },
        execute: function() {
            console.log('Modules Executing');

            for (var i = 0; i < $.readyFn.list.length; i++) {
                try {
                    $.readyFn.list[i].apply(document, [$]);
                } catch (e) {
                    throw e;
                }
            };
        }
    };

    /** [2] */
    app = {
        initSmoothState: function () {
            console.log('Module Executed: Smooth State');

            var $page = $('#main'),
                options = {
                    debug: true,
                    prefetch: true,
                    cacheLength: 2,
                    onStart: {
                        duration: 500,
                        render: function($container) {
                            // Add your CSS animation reversing class
                            $container.addClass('is-exiting');
                            // Restart your animation
                            app.smoothState.restartCSSAnimations();
                        }
                    },
                    onReady: {
                        duration: 0,
                        render: function($container, $newContent) {
                            // Remove your CSS animation reversing class
                            $container.removeClass('is-exiting');
                            // Inject the new content
                            $container.html($newContent);
                        }
                    },
                    onAfter: function($container, $newContent) {
                        $.readyFn.execute();
                    }
                };

            this.smoothState = $page.smoothState(options).data('smoothState');
        },
        initGoogleMaps: function () {
            console.log('Module Executed: Google Maps');

            this.map = document.getElementById('map');

            if (this.map) {
                if (window.google && window.google.maps) {
                    this.makeGoogleMaps();
                } else {
                    this.loadGoogleMaps();
                }
            }
        },
        loadGoogleMaps: function () {
            console.log('Module Loaded: Google Maps');

            var js, lg, fjs, id = 'google-maps-api';

            if (document.getElementById(id)) {
                return;
            }

            lg     = document.documentElement.getAttribute('lang');
            fjs    = document.getElementsByTagName('script')[0];
            js     = document.createElement('script')
            js.id  = id;
            js.src = '//maps.googleapis.com/maps/api/js?callback=app.makeGoogleMaps';
            fjs.parentNode.insertBefore(js, fjs);
        },
        makeGoogleMaps: function () {
            console.log('Module Initiated: Google Maps');

            var latlng = new google.maps.LatLng(-37.856520, 145.027979),
                isTouchDevice = !('ontouchstart' in document.documentElement),
                myOptions = {
                    zoom: 16,
                    center: latlng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                    disableDefaultUI: true,
                    zoomControl: true,
                    scrollwheel: false,
                    draggable: isTouchDevice
                },
                map = new google.maps.Map(this.map, myOptions),
                marker = new google.maps.Marker({
                    map: map,
                    position: latlng,
                    title: "Brow 101"
                });
        }
    };

    /** [3] */
    $doc.ready(function() {
        console.log('Initial Document Ready');

        app.initSmoothState();

        $.readyFn.execute();
    });

    /** [4] */
    $.fn.ready = $.readyFn.register;

})(jQuery);

/** [5] */
$(function() {
    app.initGoogleMaps();
});
```

Also, you might want to consider adding some kind of map manager: http://stackoverflow.com/a/25533112/140357

**Comment by goldtoothlogoose** [comment]
Thankyou so much mcaskill! I really appreciate the time you've taken to dissect my code and offer a solution. I've implemented the code you provided, and so far it appears to be working great. Thanks again!

I'm now just wondering where would be the best place to initialise my other plugins, as previously I was initialising them in my $(document).ready code and then calling them in the on:after smoothstate callback ( I didn't include these in the code I posted initially for the sake of simplicity). 

I took a look at the link you provided r.e. a map manager. I'm curious to know why I would potentially need one of these? I've tried zooming in and out of the map etc and coming back to the page, and everything seems to be fine (I'm also only running a single map on one of my pages, if that makes any difference).

**Comment by mcaskill** [comment]
As for the other plugins, they can be initialized _before_ or _after_ the `$.fn.ready = $.readyFn.register;`.

Plugins declared _before_ you replace jQuery's `onReady` handler will only be executed once. These handlers won't be called when using `$.readyFn.execute();`. This is useful for any JS that is used on all pages—SmoothState, scrolling, resize, clicks related to any and all (like site header links), for example.

Plugins declared _after_ you replace jQuery's `onReady` handler will execute every time you call `$.readyFn.execute();`. This is useful for page-specific features like a map, parallax, Masonry-style grids, or event just global features that need to recalculate stuff.

Another way you could use the MEC above would be to not replace jQuery's `onReady` handler and just assign all your modules that could be re-initialized to the register method directly so as to leave jQuery's `onReady` intact:

```
$.readyFn.register(function() {
    app.initGoogleMaps();
});
```

---

Regarding map management, this is only really important if you're planning on using events to interact with the map if ever its a big application.

Along this same topic, it's good practice to unbind any page-specific events during SmoothState's `onBefore()` to prevent bloat. Say you have a "About Us" page that has some scrolling events that aren't needed elsewhere, it's a good practice to unbind those if they aren't needed elsewhere.

**Comment by goldtoothlogoose** [comment]
Thanks so much man, I've got my other plugins working based on your suggestions. 

Really appreciate the help, I'm going to post this on Stackoverflow too in case anyone else is in the same position.

**Comment by sahandii** [comment]
How can i make sure a initialization only runs once throughout the whole navigation? Both from document.ready and from the global onReady function?

http://mlli.eu/form3-2/enter/
- If you click 'back' to the intro-page from the logo in the bottom-nav, some scripts get runned twice, since it already get's initialized from the page load

Link to smoothState - 
http://mlli.eu/form3-2/js/app.js

**Comment by mcaskill** [comment]
Your test page is returning a 404 so let's presume you're using the module execution controller as shown above. As I explained [previously](https://github.com/miguel-perez/smoothState.js/issues/249#issuecomment-182892125).

Technically, you don't need to replace jQuery's `.ready()` method as done above.

```
$.fn.ready = $.readyFn.register;
```

If you don't replace the jQuery's `.ready()` method, handler's passed in will be executed after the DOM is ready. And:

> If `.ready()` is called after the DOM has been initialized, the new handler passed in will be [executed immediately].
> — [jQuery API `.ready()`](https://api.jquery.com/ready/)

So, use jQuery's `.ready()` method to execute any global components. Use `$.readyFn.register()`method to execute any local components (e.g., page specific); anything that needs to be refreshed, recalculated, activated, or deactivated, should be passed to `$.readyFn.register()`.

```
[…]
    onAfter: function($container, $newContent) {
        # Execute our local handlers
        $.readyFn.execute();
    }
};

$.readyFn.register(function() {
    app.initGoogleMaps();
    app.refreshColorPalette();
});

# Execute when DOM is ready; runs once per page load
$doc.ready(function() {
    app.initSmoothState();
    app.initWaypointStickyHeader();

    # Execute our local handlers
    $.readyFn.execute();
});
```

**Comment by sahandii** [comment]
Sorry it should be working now, appreciate the help man, thanks a lot. I definitely have to dig deeper in this, i'll see if i can set it up like your explanation. Cheers!

**Comment by mcaskill** [comment]
Looking at your [app.js](http://mlli.eu/form3-2/js/app.js), the problem with the JS is that `initializeShit()` (and `initializeOtherShit()`) does everything. You run it once the DOM is ready and then you got SmoothState configured to call it every time it loads a new page, so of course everything is running more than once.

What you need to do is break down `initializeShit()` (and `initializeOtherShit()`) into two groups: _stuff that should run only once_ and _stuff that should run every time_:

```
$(function(){
    'use strict';

    var options = {
        […]
        onAfter: function($container, $newContent) {
            initializeRecurringStuff();
        }
    },
    smoothState = $('#main').smoothState(options).data('smoothState');

    initializeGlobalRunOnceStuff();
});
```
