### ISSUE TITLE
Firefox: misnamed variable is causing back button events to not work 

### ISSUE THREAD

**Issue by cee-chen** [miguel-perez/smoothState.js#255]
(Oddly enough, Chrome and IE have no problem with the incorrect variable - I only noticed this on Firefox.)

In any case, here's the issue:
https://github.com/miguel-perez/smoothState.js/blob/master/src/jquery.smoothState.js#L323

`event.state` should be `e.state`. I fixed this on my own local minified copy and confirm that renaming it the correct letter variable instead of `event.state` works.

Let me know if you'd like me throw up a test of this!

**Comment by danijelgrabez** [comment]
Same issue _(FF on Mac and Windows)_. Constance's fix worked on both platforms for me.

**Comment by kosticfilip** [comment]
Worked for me also, thanks

**Comment by medoingthings** [comment]
+1 Encountered this issue, too and Constance’s fix solves it. Would be great if this could get merged.

**Comment by mcaskill** [comment]
See #254
