### ISSUE TITLE
Prefetch won't work after clicking any anchors.

### ISSUE THREAD

**Issue by sqc1999** [miguel-perez/smoothState.js#268]
I think it is due to [this line of code](https://github.com/miguel-perez/smoothState.js/blob/master/src/jquery.smoothState.js#L721). The event handler is bind to the anchors but not the container, so it won't work after the contents in the container changed.

**Comment by sean-kennedy** [comment]
See #264 merge.

**Comment by sqc1999** [comment]
Thanks.
