### ISSUE TITLE
smoothState and slick not working

### ISSUE THREAD

**Issue by dimensi** [miguel-perez/smoothState.js#270]
If i use smoothState and Slick slider together, i take that error 
![img-2016-04-23-04-45-05](https://cloud.githubusercontent.com/assets/11390039/14758596/2f570598-090e-11e6-8758-e6c5b4fb3aa7.png)
It happens when I'm doing some switching between pages.
Sorry for my english, how fix it?
My JS code

```
$(function(){
  'use strict';
  var $page = $('#main'),
      options = {
        anchors: '.header__logo, .stolkovo-link ',
        debug: true,
        prefetch: true,
        cacheLength: 5,
        onStart: {
          duration: 1000, // Duration of our animation
          render: function ($container) {
            // Add your CSS animation reversing class
            $container.addClass('slideOutLeft');
            // Restart your animation
            smoothState.restartCSSAnimations();
          }
        },
        onReady: {
          duration: 1000,
          render: function ($container, $newContent) {
            // Remove your CSS animation reversing class
            $container.addClass('slideInRight')
            $container.removeClass('slideOutLeft');
            // Inject the new content
            $container.html($newContent);
          }
        },
        onAfter: 
          function($container, $newContent) {
            fn();
        }
      },
      smoothState = $page.smoothState(options).data('smoothState');
});
function fn () {
    $('.banner-carousel').slick({
        arrows: false,
        dots: false,
        autoplay: true,
        autoplaySpeed: 3000,
    });
    $('.new-banner').slick({
        arrows: false,
        dots: false,
        autoplay: true,
        autoplaySpeed: 3000,
    });
    $('#main-partners').slick({
        arrows: false,
        dots: true,
        autoplay: false,
        autoplaySpeed: 2000,
        slidesToScroll: 4,
        slidesToShow: 4,
        responsive: [
            {
                breakpoint: 1070,
                settings: {
                    slidesToScroll: 3,
                    slidesToShow: 3
                }
            },
            {
                breakpoint: 800,
                settings: {
                    slidesToScroll: 2,
                    slidesToShow: 2
                }
            },
            {
                breakpoint: 600,
                settings: {
                    slidesToScroll: 1,
                    slidesToShow: 1
                }
            }
        ]
    });
    $('.partners__block-slider').slick({
        arrows: false,
        dots: true,
        autoplay: false,
        autoplaySpeed: 2000,
        slidesToScroll: 1,
        slidesToShow: 1
    });
//  $('.under-menu__ul > li > a').click(function() {
//          $('title').append(' - Новый тайтл');;
//      });
    $('.tr.no-time').slideUp();
    $('.tr.section.have-child').click(function() {
        $(this).next().slideToggle();
    })

};
fn();
```

**Comment by floriannicolas** [comment]
Does it work if you don't launch fn(); in smoothState onAfter option  ?

**Comment by floriannicolas** [comment]
Ok, forget my previous question. I tested it.
Comment the following line should solve your problem : 
`// cacheLength: 5,`

**Comment by dimensi** [comment]
Hi! I thought his problem this way:

```
;(function ($) {
    $('#main').smoothState({ 
        prefetch: true,
        pageCacheSize: 4,
        onAfter: function($container, $newContent) {
            fn();
        }
    });
})(jQuery);
$(function(){
  'use strict';
  var $page = $('#main'),
      options = {
        anchors: '.header__logo, .stolkovo-link ',
        debug: true,
        prefetch: true,
        cacheLength: 5,
        onStart: {
          duration: 1000, // Duration of our animation
          render: function ($container) {
            // Add your CSS animation reversing class
            $container.addClass('slideOutLeft');
            // Restart your animation
            smoothState.restartCSSAnimations();
          }
        },
        onReady: {
          duration: 1000,
          render: function ($container, $newContent) {
            // Remove your CSS animation reversing class
            $container.addClass('slideInRight')
            $container.removeClass('slideOutLeft');
            // Inject the new content
            $container.html($newContent);
          }
        },
        onAfter: 
          function($container, $newContent) {
            location.reload();
            fn();

        }
      },
      smoothState = $page.smoothState(options).data('smoothState');
});
function fn () {
    tabby.init({
        toggleActiveClass: 'tabs__link-active'
    });
    $('.banner-carousel').slick({
        arrows: false,
        dots: false,
        autoplay: true,
        autoplaySpeed: 3000,
        speed: 1500
    });
    $('.new-banner').slick({
        arrows: false,
        dots: false,
        autoplay: true,
        autoplaySpeed: 3000,
    });
    $('#main-partners').slick({
        arrows: false,
        dots: true,
        autoplay: false,
        autoplaySpeed: 2000,
        slidesToScroll: 4,
        slidesToShow: 4,
        responsive: [
            {   
                breakpoint: 1070,
                settings: {
                    slidesToScroll: 3,
                    slidesToShow: 3
                }
            },
            {
                breakpoint: 800,
                settings: {
                    slidesToScroll: 2,
                    slidesToShow: 2
                }
            },
            {
                breakpoint: 600,
                settings: {
                    slidesToScroll: 1,
                    slidesToShow: 1
                }
            }
        ]
    });
    $('.partners__block-slider').slick({
        arrows: false,
        dots: true,
        autoplay: false,
        autoplaySpeed: 2000,
        slidesToScroll: 8,
        slidesToShow: 8
    });
};
$(document).ready(function() {
    fn();
});
```

But, I still have another problem, namely tabby.js plugin does not work until you reload the page.

**Comment by floriannicolas** [comment]
could you check my solution ? maybe it will resolve your problem with tabby.js

**Comment by dimensi** [comment]
not work(

**Comment by dimensi** [comment]
http://dimensi.ru/animation.gif
I film that bug

**Comment by mcaskill** [comment]
Hello, I haven't tested the code above nor have I tried those two together but maybe [this solution for Google Maps](https://github.com/miguel-perez/smoothState.js/issues/249#issuecomment-182408125) might help. I suggest reading the entire thread.

**Comment by plexus77** [comment]
Hi guys, I have come across this issue too, not quite sure what is going on but I believe that the slick instance is attaching itself to the contents of the smoothstate cache so that when you navigate back to a page that has a slick slider on it, slick is trying to reinitialise on top of another instance and is failing.

On the current project I am working on I have noticed that the bug only occurs when the full page load happens on a page with the slider. In this case there is a single slider on the site on the home page. 
1. load page with slider
2. navigate to another page
3. navigate back to the original page
4. slick fails to reinitialise

It doesn't happen if the full page load happens on any other page and then I navigate to the page with the slider on it, then navigate away and back to it again. Perhaps it has to do with the order of initialisation and the fact that if I initialise slick before smoothstate then the smoothstate cache will contain the slick modified dom.  

In fact I just did another test then and I had smoothstate initialising plus my page specific inits happening for the inital page load inside an onReady function and the page specifics were loading before the smoothstate instance, swapping them around seems to have fixed the issue...

**Comment by 0xsven** [comment]
This error message means that slick carousel has already been initialized. Probably coming from smoothState cache.

You can do a check to prevent it: `$(".slider").not('.slick-initialized').slick()`
[credit](https://github.com/kenwheeler/slick/issues/1953)

**Comment by sadeghbarati** [comment]
I Had This Error Before But Solved With:

function slick() {
"use strict";
    //Slick Code
};

$(document).ready(function() {
       slick();
       //Another Codes
});

$("#main").smoothState({
//...
///....

     onAfter: function($container, $newContent) {
         slick(), function1(), function2(), ......
         }
}).data("smoothState")

**Comment by heyzombie** [comment]
maybe the best solution, and works, is here in my case:
` onAfter: function() {
			 reloading();			 
		  }

function reloading() {
		skrollr.init().destroy();
		setTimeout(function() {
			skroolr();
		}, 200);
	}`

**Comment by rftb** [comment]
Been stuck on this same issue for 2 whole days... finally figured out the full solution that worked for me using some of the advice above plus a little extra I added.

In smoothState's onStart callback, I unslicked the slider, set a variable equal to the html content of the (now unslicked) slick slider (the div with classes `slick-initialized` and `slick-slider`). Once set, I removed the content completely.

In smoothState's onAfter callback, I removed the `slick-initialized` and `slick-slider` classes from the slider div (those are re-included on the div because of smoothState's cache), then re-inserted the html content, and re-called the initial `slick()` function.

Also please note, if you set the cacheLength to 0, the back button will not work properly, just fyi.

My code:
```javascript
var projectsSliderContent;

function scripts() {
    jQuery('.projects').not('.slick-initialized').slick({
        ...
    });
}

$(function() {
    'use strict';
    var smoothState = $('#page').smoothState({
        cacheLength: 10,
        onStart: {
            duration: 1000,
            render: function($container) {
                $container.addClass('is-exiting');
                smoothState.restartCSSAnimations();
                setTimeout(function() {
                    $('.projects').slick('unslick');
                    projectsSliderContent = $('.projects').html();
                    $('.projects').html('');
                }, 1000); // set delay equal to duration
            }
        },
        onAfter: function($container, $newContent) {
            $container.removeClass('is-exiting');
            $('.projects').removeClass('slick-initialized slick-slider').html(projectsSliderContent);
            scripts();
        },
    }).data('smoothState');
});
```
