### ISSUE TITLE
Materializecss select problem

### ISSUE THREAD

**Issue by mathsymbols** [miguel-perez/smoothState.js#273]
I am using smoothstat on [this web page](http://ders34.com/tpl_cat_ozelders.html). 
"Materializecss Select" does not work. Make the transition to other pages when I came back again.

[Materializecss Select ](http://materializecss.com/forms.html#select)

**Comment by floriannicolas** [comment]
Hi, 
The simpliest solution for your problem is to add this in your smoothState options onAfter method : 

``` javascript
onAfter: function ($container, $newContent) {
           // REINIT THE materializecss SELECT
           $('select').material_select();
}
```

PS : Sometimes I had to use this in a setTimeout method. But I don't think so in your case.

**Comment by mathsymbols** [comment]
it worked. thnak you so much.
