### ISSUE TITLE
Pages not going 'back to top' between page transitions

### ISSUE THREAD

**Issue by mitchrenton** [miguel-perez/smoothState.js#277]
Hi Miguel,

I've setup smoothState and I love it. I just have an issue;

When I click a link and go from one page to another, the destination page is at the same scroll level as the origin page. I'd expect the page to go back to top, like a traditional link.

I don't see anything in the options that could solve the issue. Here is my setup...

```
$(function(){
  'use strict';
  var $page = $('#js-transition'),
      options = {
        debug: true,
        prefetch: true,
        cacheLength: 2,
        forms: 'form',
        onStart: {
          duration: 200, // Duration of our animation
          render: function ($container) {
            $container.addClass('is-exiting');
            smoothState.restartCSSAnimations();
          }
        },
        onReady: {
          duration: 0,
          render: function ($container, $newContent) {
            $container.removeClass('is-exiting');
            $container.html($newContent);
          }
        },
        onAfter: function() {
          prep();
        }
      },
      smoothState = $page.smoothState(options).data('smoothState');

});

$(document).ready(function(){
  prep(); 
});

function prep(){
  var nav = responsiveNav(".nav-collapse", {
    insert: 'before'
  });
}
```

Hopefully this is something straight forward!

**Comment by mitchrenton** [comment]
Ok, after some debugging, I've seen that it's actually the CSS that is causing the back to top to fail. 100% height on an element seems to confuse the plugin.

I used the suggesting from #210 , using `vh`as the unit as opposed to `%`.

**Comment by sebastiangraz** [comment]
Sorry for posting in a closed ticket. Im just curious which element of your page was 100% in height? Is it any element? Im experiencing the same problem
