### ISSUE TITLE
Custom ajax request fires multiple times

### ISSUE THREAD

**Issue by vk011** [miguel-perez/smoothState.js#278]
I make an ajax request upon click of a link, and without smoothstate it works as it should, however with smoothstate it fires multiple times. Any way to avoid this?

Basically this specific request should load a set number of results on each click of a.storiesmore, and without smoothstate it loads a few items each time, but with smoothstate enabled it fires multiple times and loads everything at once.

```
$body.on('click', 'a.storiesmore', function(e) {
    e.preventDefault();

    var nbhd_id = $(this).data('id');
    var cat = $(this).data('cat');

    var down = $window.scrollTop();

    $this = $(this);

    // get more stories
    $.ajax({
            type: "POST",
            async: true,
            url: ajax_object.ajax_url,
            data: {
                nbhd_id: nbhd_id,
                cat: cat,
                action: 'GET_MORE_STORIES'
            },
            // dataType: "json",
            cache: false,

            beforeSend: function() {
                $this.find('span.spin').addClass('show');
                // $('div.morestories').isotope('destroy');
                // $('.storiesiso').addClass('hide');
            },

            success: function(response){

                var items = $(response);
                for (var i = items.length - 1; i >= 0; i--) {
                    $('.storiesiso')
                        .isotope('insert', items[i] ).isotope();
                };
            },

            complete: function() {
                $this.parent().hide();

                $this.find('span.spin').removeClass('show');

            }
    }); // end ajax
```

**Comment by johanneslamers** [comment]
have you blacklisted the `a.storiesmore` in the smoothState options?

```
$(function () {
    'use strict';
    var $page = $('#main'),
        transition = "fade",
        options = {
            debug: true,
            prefetch: true,
            blacklist: '.storiesmore',
```

**Comment by vk011** [comment]
Hello,

Yes, like so:

```
$('#main').smoothState({

        anchors: 'nav a',
        blacklist: '.storiesmore, .fancybox, .filters-overlay h3 a',
```

However it seems to have no effect. The .storiesmore anchor element gets generated on the fly after a custom ajax request, could this be the issue? 

I've had this multiple firing problem elsewhere, and then I replaced `$body.on('click', 'a.something', function(e) {` with `$('.something').click(function(e) {` so that it doesn't work after ajax and all that works, but `.storiesmore` needs to work after ajax because as I said it gets generated after a custom ajax request.

**Comment by vk011** [comment]
I've rewritten that part to not create the link on the fly and now it's good. 

Either way if it would be possible to also detect on the fly created elements with `blacklist` would be good. Great plugin, thanks!
