### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [miguel-perez/smoothState.js#287]
.

**Comment by mcaskill** [comment]
I would recommend reading this: #249 to understand how to use the readyExec and how to organize your code around SmoothState.

You've got a lot going on throughout your JavaScript which you would benefit from reorganizing. This is especially important when using a library like SmoothState to dynamically change pages. It's easy to collect garbage (e.g., event listeners) while navigating from one page to another.

**Comment by luigizinodaur** [comment]
@mcaskill it's not my code, and I'm not well versed enough in Javascript to redo the scripts. :(
