### ISSUE TITLE
Using the back button makes the page jump to the top before the animation

### ISSUE THREAD

**Issue by arnaudthuillier** [miguel-perez/smoothState.js#357]
Hello,

First of all, thanks @miguel-perez for that awesome plugin 👍 

Here is my problem :
Imagine I'm at the bottom of a page, when I click on the back button the page jumps to the top before firing the animation.

Live problem on my website : [http://arnaudthuillier.com/](url)
And on the sidebar demo : [https://rawgit.com/miguel-perez/smoothState.js/master/demos/sidebar/index.html](url)

I'd just like the current page to stay still before it fires the animation.
Is it somehow possible ?

**Comment by irabronson** [comment]
`		if ('scrollRestoration' in history) {
			history.scrollRestoration = 'manual';
		}
`

**Comment by arnaudthuillier** [comment]
Thank you so much @irabronson !
