### ISSUE TITLE
The demo link is redirected to virus website

### ISSUE THREAD

**Issue by bofeiw** [miguel-perez/smoothState.js#374]
Seems the link is down! Please fix.
<img width="1126" alt="link is down" src="https://user-images.githubusercontent.com/34177142/54874587-85234500-4e42-11e9-9261-fa51969d1b99.png">

**Comment by lenamtl** [comment]
This link should be removed and virus cleaned ASAP

**Comment by bofeiw** [comment]
> This link should be removed and virus cleaned ASAP

Seems this repo has been inactive for some years

**Comment by lenamtl** [comment]
I have contacted the author

**Comment by bofeiw** [comment]
Hey @lenamtl have the author replied you?

edit: it seems yes as the link is removed.

**Comment by lenamtl** [comment]
yes
