### ISSUE TITLE
Cross - Browser Problem

### ISSUE THREAD

**Issue by leifniem** [miguel-perez/smoothState.js#48]
First of all: Great idea and great script, but i am experiencing issues with browsers other than Chrome.

In Firefox the following happens:
![firefox-issue](https://cloud.githubusercontent.com/assets/5417518/4008132/93b7e880-29d2-11e4-8639-df2a5734ca27.gif)

In Safari / Webkit the animations do not trigger at all (this may be for me being a noob).

System is OS X 10.9.4 with Chrome 36, Firefox 31, Safari 7.0.6

Sorry if those issues are my failure.

**Comment by jonasll** [comment]
I am seeing this exact issue on FF and Safari. Chrome handles the transitions and loading properly.
