### ISSUE TITLE
Invalidating cache

### ISSUE THREAD

**Issue by geldmacher** [miguel-perez/smoothState.js#51]
Do we need a solution for invalid caches?

Example:
An user is using a shop system. The merchant changes product data of an product the user just saw seconds ago. If there is no smoothState.js the user just gets new version of this product the next time he return. With smoothState.js the user gets the old version. Am i wrong with this?

If not, how can we handle this? Just say, that for example shop system should not use smoothState.js or do we need some sort of request which asks the server if the local cache is still valid?

**Comment by chaenu** [comment]
Hey @snap608,

How did you finally solve this problem? Is there a work-around I can use until we agree here on an improvement?

**Comment by miguel-perez** [comment]
A cache clearing method has been added: https://github.com/miguel-perez/smoothState.js#clearurl
