### ISSUE TITLE
Conflict Issue

### ISSUE THREAD

**Issue by rwgstudio** [miguel-perez/smoothState.js#54]
EDITED:

OK, I've edited my request for help because the last one wasn't very specific :)

I've got this installed and working beautifully in a WordPress site I'm building.
Animations and everything is working great. The site uses InfinateScroll, a basic Timer CountDown script and a js mobile menu (amongst others). I'm getting issues with these when using SmoothState. 

Basically when you navigate to a page using either feature, they don't work unless the page is refreshed? Below, I've pasted the code I'm using to load the script - It also uses the fix from Alan Parsons.

Any help would be great, thanks.

``` js
///////////////////////////////
// SmoothState
///////////////////////////////
(function($) {
    var $body = $('html, body'),
    content = $('#page').smoothState({
        prefetch: true,
        pageCacheSize: 4,
        onStart: {
            duration: 250,
            render: function (url, $container) {
                content.toggleAnimationClass('is-exiting');
                $body.animate({
                    scrollTop: 0
                });
            }
        },
        onEnd : {
            duration: 0,
            render: function (url, $container, $content) {
                $body.css('cursor', 'auto');
                $body.find('a').css('cursor', 'auto');
                $container.html($content);
                $(document).ready();
                $(window).trigger('load');
            }
        },
        onAfter : function(url, $container, $content) {
        }
    }).data('smoothState');
})(jQuery);

///////////////////////////////
// jquery.ready fix
///////////////////////////////
(function($, undefined) {
    var isFired = false;
    var oldReady = jQuery.fn.ready;
    $(function() {
        isFired = true;
        $(document).ready();
    });
    jQuery.fn.ready = function(fn) {
        if(fn === undefined) {
            $(document).trigger('_is_ready');
            return;
        }
        if(isFired) {
            window.setTimeout(fn, 1);
        }
        $(document).bind('_is_ready', fn);
    };
})(jQuery);
```

**Comment by martijnvhummel** [comment]
@miguel-perez 
Is there no 'proper' solution for this problem yet? Using a smoothstate parameter for example?
Just for the cleanliness of the code and to prevent potential problems, I prefer to keep the WP body classes in the body element, not in a div within the #m-scene element. So if there is a way to refresh the body classes, that would be swell!
