### ISSUE TITLE
Doesn't work unless going to .html page

### ISSUE THREAD

**Issue by NetOpWibby** [miguel-perez/smoothState.js#59]
I was thinking I could use this plugin on my sites, but my sites don't have "index.html" in the URL bar. Every link ends with a forward slash. Is it possible to make it work for me?

**Comment by andydlin** [comment]
@NetOperatorWibby i know it's been almost 4 years, but i wanted to ask: does smoothstate.js work with Jekyll?

**Comment by NetOpWibby** [comment]
@andydlin Haha, I have no idea. I've moved onto creating sites with my Express/Feathers boilerplates:

- https://paulwebb.software/NetOperatorWibby/ExpressBoilerplate
- https://paulwebb.software/NetOperatorWibby/FeathersBoilerplate
