### ISSUE TITLE
How to integrate SmoothState with Wordpress at all?

### ISSUE THREAD

**Issue by ghost** [miguel-perez/smoothState.js#64]
There are few problems with that.

There is one of you that have a complete and serious guide?

For example: I use in my Wordpress both "Visualizer" plugin (that visualize Google Charts in my pages) and "DataTables" plugin of jQuery.

Both aren't working when I use SmoothState.

When I call a page in wordpress that contain one of these from my home page nothing works. The page is blank. Without code. If I refresh browser on that page then everything works.

I suppose the problem is with ajax call of the plugins, but I'll never find a solution. That's why I'm here asking you...

HOW TO?

**Comment by zakirsajib** [comment]
http://sandbox.lattitudebd.com/
