### ISSUE TITLE
Add an option to change the container for anchors

### ISSUE THREAD

**Issue by LuminusDev** [miguel-perez/smoothState.js#65]
In relation with #35 

I wonder if change the container for anchors is interesting.
This can be in the options, if someone needs to have this feature absolutely.

It's easy to implement, I have already test it. But this functionality will require a good documentation to make people understand container for anchors can't be in original container (obviously disappears binding).

So, useful ?

**Comment by lost-end-found** [comment]
load() was very helpful and it would help for some folks (like me) to have an example in the read.me probably. Awesome work 👍
