### ISSUE TITLE
Javascript Event Handlers

### ISSUE THREAD

**Issue by neon64** [miguel-perez/smoothState.js#73]
On my page I attach several events to elements within the smoothState container. Do I need to bind those events again after I load a new page?

Here is my code so far (it is CoffeeScript):

```
registerEvents()

smoothState = $("#page").smoothState({
    anchors: ".Link--smoothState"
    onStart: {
        duration: 250
        render: (url, container) ->
            smoothState.toggleAnimationClass('Page--isExiting')
            $("html, body").animate({ scrollTop: 0 })
            return
    },
    onEnd: {
        duration: 0
        render: (url, container, content) ->
            $("html, body").css('cursor', 'auto');
            $("html, body").find('a').css('cursor', 'auto');
            container.html(content);
            return
            # do I need to add registerEvents() here?
    }
}).data('smoothState');
```

All of my JavaScript files are outside of the container element, so they should only be running once, right? Or is it intended for them to be placed inside the container?

**Comment by polikin** [comment]
I tried this:

```
<body id="main>
    <script type="text/javascript" src="/assets/scripts/libs/leaflet.js"></script>
</body>
```
My script is not re-evaluated, but it's inside the container..

**Comment by rolandschuetz** [comment]
leaflet.js looks like it's just the maps library. Why would you want to load a library twice?

You statement is way to vage to give you some specific help. Do you have an demo of this?

**Comment by polikin** [comment]
Well.. this is an example. But thanks for the reply. I think I understand something now. :P

**Comment by rolandschuetz** [comment]
This is not an example. When I copy&paste that in an html-page nothing happens. I can not see how you have configured smoothState, I also don't know what's in leaflet.js and I have no idea how you see that what you expect doesn't happen.

If you want free help please put some effort in me helping you as well. Can you submit a reduced test case to help us debug this? Here are some guidelines: https://github.com/weblinc/jquery.smoothState.js/blob/master/README.md#how-to-ask-for-help
