### ISSUE TITLE
Redrawing of element creates flickering

### ISSUE THREAD

**Issue by rolandschuetz** [miguel-perez/smoothState.js#75]
__smoothState.js version tested:__
 - Version 0.5.2

__Browser versions or Packager version tested against:__
 - IE11
 - Chrome
 - Safari

__Description:__
 - The plugin triggers as part of triggerAllAnimationEndEvent on line 271 a redraw of the main element. But this creates a flickering on the page on my site. Disabling this line removes the flicker. Any idea how to fix this?

__The result that was expected:__
 - Smooth transition between pages

__The result that occurs instead:__
 - Transition causes ugly flickering

Why is the redraw needed?

Thanks,
Roland

**Comment by miguel-perez** [comment]
@rolandschuetz is this still a problem? Do we have a test case?

**Comment by rolandschuetz** [comment]
Is this now fixed?

**Comment by miguel-perez** [comment]
@rolandschuetz I haven't seen this issue for a while. I assumed #99 fixed the problem. Is this not the case?

**Comment by rolandschuetz** [comment]
@miguel-perez Oh, I missed that you already merged. Perfect, then this issue is solved.
