### ISSUE TITLE
npm, bower or cdn?

### ISSUE THREAD

**Issue by iskrisis** [miguel-perez/smoothState.js#8]
Is smoothState on npm or some public cdn?

What about adding it to http://cdnjs.com/ (i guess then it has to be a npm package)? Just for quick development hacking around. 

Maybe not worth the time. Who knows.

**Comment by mesmerizedchild** [comment]
Hi,

Maybe old news, but if anybody is still interested, here comes the CDN for jquery.smoothState.min.js:

<script src="https://cdn.rawgit.com/miguel-perez/smoothState.js/master/jquery.smoothState.min.js"></script>

Ciao :) !

**Comment by mesmerizedchild** [comment]
Hi!

Maybe it's old news, but here comes the URL to download the [minified] version of smoothState.js from the RawGit CDN:

https://cdn.rawgit.com/miguel-perez/smoothState.js/master/jquery.smoothState.min.js

Ciao :) !
