### ISSUE TITLE
smoothState.js version is our of sync.

### ISSUE THREAD

**Issue by rolandschuetz** [miguel-perez/smoothState.js#84]
The different configuration claim different smoothState versions:
https://github.com/weblinc/jquery.smoothState.js/blob/master/bower.json
https://github.com/weblinc/jquery.smoothState.js/blob/master/smoothState.jquery.json

**Comment by FND** [comment]
possibly related: the [Getting Started](http://weblinc.github.io/jquery.smoothState.js/getting-started.html) page links to @miguel-perez's repo, which seems to lag behind this (apparently official) one
