### ISSUE TITLE
Usage advice needed

### ISSUE THREAD

**Issue by phpMagpie** [miguel-perez/smoothState.js#9]
First of all .. thanks for releasing this, once I understand how to use it properly, I'll be using it on various projects :)

I need some help using this on http://precept2.highten.co.uk.  The site opens with a bootstrap 3 carousel which allows the user to scroll horizontally through each section's 'splash' type content.

When the user clicks on the down arrow from any carousel item I want smoothState to fetch the relevant section's content, smoothly scroll the carousel up off the screen whilst the new page content scrolls up onto the screen.
1. I have this working to some extent, but the animation is far from smooth.  How do I make this scroll smoothly, giving the illusion that the relevant content was waiting below the carousel all the time and simply scrolls up into the space the carousel was occupying?
2. When I activate smoothScroll the left and right links in the bootstrap carousel stop working, even thought they have classes of no-smoothstate [edited to correct typo].
3. Is there a way of only linking smoothstate to specific links?  E.g. a whitelist rather than a blacklist?

Thanks, Paul.

**Comment by jandagroup** [comment]
@phpMagpie almost 2 years later and I find myself with needing a similar interaction model (almost exactly how you described it!). Any chance you're able to share how you accomplished this? The old url is no longer active. Any help that you can provide would be greatly appreciated.  

Thanks!

**Comment by PaulPrecept** [comment]
@jandagroup sorry, this project didn't go live using smoothState and I've not ended up using it on any other projects.  I've not kept a backup of the code anywhere either :(
