### ISSUE TITLE
The alternate-reverse portion of the animation doesn't seem to be working

### ISSUE THREAD

**Issue by glennpot** [miguel-perez/smoothState.js#90]
I have smoothState running on a custom Wordpress template, with the help of the Alan Parsons WP/SS post. I can see that the .is-exiting class is being added to the container for a moment when I go 'back', but the animation fails completely in reverse. I've added all -webkit-, -moz-, -ms-, and -o- transition prefixes.

There are three pages in this demo - http://bit.ly/1CBvZJi - /secret, /secret2 (recipes) and /secret3 (me).

Can someone take a peek and let me know what I'm missing? The smoothState script call was added to the functions.php file _after_ the script.js call, but I switched that and it didn't help.

**Comment by brainra** [comment]
Thank you, this helped a lot, I had the same problem.

**Comment by glennpot** [comment]
Awesome! Glad this helped someone.

**Comment by chrisjansky** [comment]
Brilliant, thanks for the fix @glennpot! Got my head spinning for a couple of hours trying to fix that.

**Comment by proov** [comment]
I have the same issue. But why the classic way doesn't work ? i've seen a lot of people having this issue... but if changing animation-direction property doesn't restart the animation why is it working on the smoothState site ?
