### ISSUE TITLE
Cache fails if other urls are prefetched during the onStart transition

### ISSUE THREAD

**Issue by hjvedvik** [miguel-perez/smoothState.js#95]
__smoothState.js version tested:__
 - Version 0.5.1

__Description:__
Cache is cleared before transition ends.

__Steps to reproduce the problem:__
Set prefetch to true. Click a link and then quickly hover another link before the transition has ended. This will make the cache fail. I use a [GreenSock](https://greensock.com/) timeline to animate stuff in and out.

__The result that was expected:__
The link that is clicked should be loaded and replace existing content.

__The result that occurs instead:__
Gets an error on line 395 `Cannot read property 'html' of undefined ` and content is not replaced.

__Possible solution:__
I'm not sure what's the best solution here, but I might have some time to look into the code for a solution after my project is done. I just check if transition has started on every hover to fix this for now.

**Comment by miguel-perez** [comment]
@hjvedvik have you made any progress on this issue? let us know.

**Comment by miguel-perez** [comment]
I've [disabled fetching](https://github.com/miguel-perez/smoothState.js/commit/02cfc2b5b1b5dd11379f9581e1b30956cdb6118d) while a page is being transitioned, this should take care of this edge case.
