### ISSUE TITLE
Wait till images are loaded before running 'onEnd' ?

### ISSUE THREAD

**Issue by AllanD** [miguel-perez/smoothState.js#98]
I noticed that the onEnd parameter fires after the dom is finished, but the images are still loading.

How would I use [https://github.com/alexanderdickson/waitForImages](https://github.com/alexanderdickson/waitForImages), or any other solution,

so that onEnd doesn't run until images are finished loading?

**Comment by kevinchevallier** [comment]
Hey @rolandschuetz , any chance you got an example working? I've been trying for a while to get smoothstate injecting the content only after the images got loaded but without luck so far. 

For example, this test in the render of the onEnd:

``` javascript
$content.waitForImages(function() {
    console.log('All images have loaded.');
}, function(loaded, count, success) {
   console.log(loaded + ' of ' + count + ' images has ' + (success ? 'loaded' : 'failed to load') +  '.');
});
```

loops twice the first console.log and doesn't fire the second one.

**Comment by rolandschuetz** [comment]
Sorry, I have no experience with that plugin

**Comment by miguel-perez** [comment]
@AllanD have you been able to work this out? Is there any information you could share with @kevinchevallier?
